### ISSUE TITLE
npm-ducttape fails if there are non-pruned npm modules

### ISSUE THREAD

**Issue by trevoro** [DeadAlready/npm-ducttape#1]
As described.

If there are npm modules which are marked as 'erroneous' then npm shrinkwrap will fail.
Suggest we just print up a nicer error message.

What do you think?

**Comment by DeadAlready** [comment]
I agree, the error message is not the best ATM.

Running _npm shrinkwrap_ with execSync does not return the error it gets in any shape size or form that I know. So while I do know it fails I have no information about how.

I will dig deeper to find if I can get the information and come up with a better message.

**Comment by DeadAlready** [comment]
# 099526b945b664303ae2e2ea3d52c3a6c158a8a1

Letting shrinkwrap highjack the terminal and output it's error in v1.0.4
