### ISSUE TITLE
Slow/unresponsive

### ISSUE THREAD

**Issue by fernandofranca** [DeadAlready/npm-ducttape#2]
I've tried npm-ducttape on a docker container and had kill it after several minutes. 

It found abot 900 dependencies. All generated TGZ files have 0 bytes.

**Comment by DeadAlready** [comment]
Never tested it inside a docker container...

Will look into it.

**Comment by DeadAlready** [comment]
Probably missing your usecase - please you describe in more detail exactly how you got the problem

**Comment by fernandofranca** [comment]
I'm using the node:6.2.1 docker image.

The app folder is mounted with "volumes_from" another container which acts as a data container. No other folder in the node container is writable by the node user.

The current modules in my package.json are:

```
  "dependencies": {
    "archiver": "^1.0.0",
    "asyncawait": "^1.0.3",
    "bcrypt": "^0.8.7",
    "beepbeep": "^1.2.0",
    "callsite-record": "~3.2.0",
    "connect-redis": "~3.1.0",
    "ejs": "2.3.4",
    "file-type": "~3.8.0",
    "fb": "~1.1.1",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "handlebars": "^4.0.5",
    "hashids": "1.0.2",
    "include-all": "^0.1.6",
    "mailgun": "^0.5.0",
    "minimist": "^1.2.0",
    "rc": "1.0.1",
    "recaptcha": "^1.2.1",
    "sails": "~0.12.3",
    "sails-disk": "~0.10.9",
    "sails-memory": "~0.10.7",
    "sails-mysql": "~0.11.5",
    "sails-redis": "~0.10.7",
    "sharp": "^0.15.0",
    "stack-trace": "0.0.9",
    "winston": "^2.2.0",
    "winston-google-analytics": "^1.0.0"
  },
  "devDependencies": {
    "sync-files": "^1.0.3",
    "nodemon":"^1.9.2"
  }
```

**Comment by DeadAlready** [comment]
I'm still a bit confused.
First: Why do you run ducttape inside the docker container? ducttape is meant for development packaging and then you would use local files during NPM install when building the container. Or am I misunderstaning?

Second: If the folder where you run ducttape is not writable, did you point the ducttape output to a writable area?

**Comment by fernandofranca** [comment]
1) I usually use docker as development environment to avoid installing more stuff (mysql, redis, nginx, for instance) on my system and to avoid discrepancies with the production environment. My development environment is Mac OS (I should've made a mention before) and usually the production environment is Linux. 

2) The folder where the app runs and where I run ducttape IS writeable (that's only writeable folder for the node user).

**Comment by DeadAlready** [comment]
Ah ok..

Will invest time into reproducing the situation. Hang tight.

**Comment by DeadAlready** [comment]
So far I have been unable to reproduce the issue - which probably means I'm doing something differently.

Can you give more details about your setup or the relevant parts of your Dockerfile?

_PS. Excuse my slowness - my experience with docker is limited to say the least._

**Comment by fernandofranca** [comment]
The issue is more related to my Docker environment complexity than npm-ducttape. 
I've built a simpler container and it created the TGZs as expected. 
My bad.
