### ISSUE TITLE
Installing a project that uses ducttape hits npm http endpoints

### ISSUE THREAD

**Issue by megawac** [DeadAlready/npm-ducttape#3]
I noticed a difference installing a project using `shrinkpack` vs `ducttape`, with shrinkpack no npm end points get hit whereas installing the same project with `ducttape` each projects metadata gets resolved.

I made a simple repro here if you want to test:

https://github.com/megawac/ducttape-http-test

Run the following:

``` bash
$ npm install
$ npm run ducttape
$ rm -rf node_modules
$ npm install --loglevel=http
# Lots of http requests

$ npm install
$ npm run shrinkpack
$ rm -rf node_modules
$ npm install --loglevel=http
# no http requests
```

Any thoughts @DeadAlready?

On another note, I've run into other issues with shrinkpack which ducttape handles significantly better :)

**Comment by DeadAlready** [comment]
Ok.. Looked into it and found the problem...
It's the --dev flag. 

npm-ducttape does not need npm shrinkwrap to be run prior, as it clears the shrinkwrap file and runs it internally, but it does so without the --dev flag at the moment.
Running shrinkwrap in this situation without the dev flag will result in everything except the devDependencies being added to the shrinkwrap file and as such when running install again the npm-ducttape and shrinkpack modules are missing (but their dependencies are not - another fun quirk of npm).

I will add an option to include the --dev flag.

**Comment by megawac** [comment]
Awesome, thanks for looking into it so quickly

**Comment by JamieMason** [comment]
> On another note, I've run into other issues with shrinkpack which ducttape handles significantly better :)

Hi @megawac, if you could add something to [shrinkpack/issues](https://github.com/JamieMason/shrinkpack/issues) I will do my best to try and improve things for you and others – thanks for checking it out.

Keep up the great work on npm-ducttape @DeadAlready 👍  we need more tools like this.
