### ISSUE TITLE
Doesn't pickup packages prefixed with `@`

### ISSUE THREAD

**Issue by megawac** [DeadAlready/npm-ducttape#5]
Packages prefixed with `@` do not make it into the `.packages/` folder but gets written to the shrinkwrap correctly.

Offending package for me was `@mapbox`

**Comment by DeadAlready** [comment]
Apologies for the delay in communication - I was on a vacation of sorts. If you would answer my questions about your use of regex, then I'll merge the pull request and push a new version out.

**Comment by megawac** [comment]
No worries, I didnt expect you to look at this over the weekend
